apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: org1-prod
spec:
  releaseName: wordpress
  interval: 5m
  chart:
    spec:
      chart: wordpress-oci        # <--- references HelmChart
      sourceRef:
        kind: HelmChart           # <--- only HelmChart, not OCIRepository
        name: wordpress-oci
        namespace: flux-system
  values:
    wordpressUsername: admin
    wordpressPassword: password123
    wordpressEmail: admin@example.com
    wordpressBlogName: "My Blog"

    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: flux.test.com
      annotations:
        kubernetes.io/ingress.class: nginx
