apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami-wordpress
  namespace: flux-system
spec:
  type: oci
  url: oci://registry-1.docker.io/bitnami/wordpress
  interval: 10m
