apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
  namespace: org1-prod
spec:
  releaseName: wordpress
  interval: 5m
  chart:
    spec:
      oci:
        image: oci://registry-1.docker.io/bitnami/wordpress
        tag: sha256-7ba39da1246c9e4a9ee33093566af03d63f465ac14bb4799e3722bdc07b69db0   # specify the chart version you want
  values:
    wordpressUsername: admin
    wordpressPassword: password123
    wordpressEmail: admin@example.com
    wordpressBlogName: "My Blog"

    service:
      type: ClusterIP

    ingress:
      enabled: true
      ingressClassName: nginx
      hostname: flux.test.com
      annotations:
        kubernetes.io/ingress.class: nginx
