apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: website
  namespace: org1-prod
spec:
  interval: 5m
  chart:
    spec:
      chart: ./apps/base/org1
      sourceRef:
        kind: GitRepository
        name: flux-demo
        namespace: flux-system

  values:
    replicaCount: 3

  valuesFrom:
    - kind: ConfigMap
      name: website-values
