# infrastructure/configs/helm-repositories.yaml
apiVersion: source.toolkit.fluxcd.io/v1b
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  url: https://kubernetes.github.io/ingress-nginx
