---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: bitnami-wordpress
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/wordpress
---
